### ISSUE TITLE
Heh, the repo name makes it sound like coala is fighting your crappy code :D

### ISSUE THREAD

**Issue by underyx** [coala/coala-vs-code#11]
That's all I wanted to say, close as invalid whenever you want :D

**Comment by gaocegege** [comment]
😄 Maybe we'll rename this repo after https://github.com/coala/coala-vs-code/issues/3.

Thanks for your advice.

**Comment by underyx** [comment]
No, don't, this name is perfect! :D

**Comment by gaocegege** [comment]
Alright :-D
