### ISSUE TITLE
Add more tests about other languages

### ISSUE THREAD

**Issue by gaocegege** [coala/coala-vs-code#12]
Now coala-vs-code only have tests on python, actually it should support much more languages.

**Comment by jayvdb** [comment]
list of languages is at https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers.

In addition to the ones at https://github.com/coala/coala-vs-code/pull/76 , coala bears also support

dockerfile
git-commit 
json
latex
jade
shellscript
typescript
tex
xml
yaml

**Comment by jayvdb** [comment]
Done in https://github.com/coala/coala-vs-code/pull/76
