### ISSUE TITLE
CI: Add coala in CI

### ISSUE THREAD

**Issue by gaocegege** [coala/coala-vs-code#22]
Now our builds on Travis CI does not check coala issues.

**Comment by kiryteo** [comment]
Can I work on this.?

**Comment by kiryteo** [comment]
How can I proceed and what is the expected outcome for this.?

**Comment by gaocegege** [comment]
@kiryteo 

There are some errors when we use coala: #23 , but you do not need to deal with them. This issue is to import coala into Travis CI build, so if you could add `coala --ci` into the config yaml file, and it works, then it works for me.

**Comment by kiryteo** [comment]
I tried adding '-run coala --ci' in the travis.yml file but the build fails..

**Comment by gaocegege** [comment]
@kiryteo 

Year but it does not matter. It is caused by #23 and you could file the PR and I will review and merge it if it could report errors in the CI build.

**Comment by kiryteo** [comment]
I'll make the PR with modified travis.yml file..

**Comment by Makman2** [comment]
Btw: I've enabled coala analysis via gitmate, I hope it works for future PRs too (but I haven't seen it on the PRs yet, so let's do this issue anyway)
