### ISSUE TITLE
Repo code inconsistent with released version

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala-vs-code#28]
Hi, I tried to fork this repo, set up the dev environment, and launch the extension in VS Code but failed due to some compilation error. Then I downloaded coala plugin from VS Code marketplace and compared code on github and that in ```~/.vscode/extensions/coala.coala-0.0.10```. It turns out that many source files are inconsistent.

I suspect that the code in this repo belongs to an older version. I simply copied the code from ```coala.coala-0.0.10``` to my forked repo and redo things again: I set up the dev environment, and launch the extension in VS Code. It works perfectly.

**Comment by gaocegege** [comment]
Do you mean the code in the repo could not be compiled successfully while the released version could?

**Comment by li-boxuan** [comment]
@gaocegege sorry, my bad, I checked again just now. Although my VS Code is complaining about a build error regarding [these two lines](https://github.com/coala/coala-vs-code/blob/master/vscode-client/src/extension.ts#L28-L29), it still works.

> Argument of type '{ reader: Socket; writer: Socket; }' is not assignable to parameter of type 'ChildProcess | StreamInfo | PromiseLike<ChildProcess | StreamInfo>'.
  Type '{ reader: Socket; writer: Socket; }' is not assignable to type 'PromiseLike<ChildProcess | StreamInfo>'.
    Property 'then' is missing in type '{ reader: Socket; writer: Socket; }'.

So both versions work (except my editor doesn't complain about the released version). Btw, I wonder which version is the up-to-date one?

**Comment by gaocegege** [comment]
I think master is the latest version.

I guess that the error is raised because startLangServerTCP is called. And in the online version we use stdio instead of TCP socket.

**Comment by gaocegege** [comment]
TCP is only for debug purpose, I changed it to stdio when I release the version. I think that is why the code is not consistent.

**Comment by li-boxuan** [comment]
Thanks. Seems the released version is not up-to-date. I'll close this issue.
