### ISSUE TITLE
langserver.py: Fix typo

### ISSUE THREAD

**Issue by stellargo** [coala/coala-vs-code#30]
In the `serve_did_save` function, fix documentation to `Serve for did_save request.`

**Comment by himanshuc3** [comment]
I would like to take this up.

**Comment by jayvdb** [comment]
Just noting that Himanshu has already done a newcomer issue, so this issue is still available for newcomers.

**Comment by manangoel99** [comment]
Can I work on this issue?

**Comment by jayvdb** [comment]
This file has been removed from the repository.
