### ISSUE TITLE
Diagnostic column number violates LSP convention

### ISSUE THREAD

**Issue by li-boxuan** [coala/coala-vs-code#37]
Diagnostic generated by current LS is as follows:
![jietu20180330-222158](https://user-images.githubusercontent.com/25746010/38158792-159f9f24-3469-11e8-8670-4270df69f029.jpg)
Note that 'character' is **null**. However, according to [LSP Specification](https://microsoft.github.io/language-server-protocol/specification), line position and character offset should be **numbers**. In fact, current LS works for VS Code but not for vim. Fixing this issue would help.

Moreover, they should be zero-based according to LSP. Comments in diagnostic.py should be updated.

I would like to solve this issue.

**Comment by gaocegege** [comment]
Thanks for your issue, and I think we could add a check for it.

Do you mind fixing the issue?

**Comment by li-boxuan** [comment]
I'm willing to fix it.

**Comment by gaocegege** [comment]
Thanks, I think it is better to follow the upstream (microsoft LSP specification), instead of the specific editor's convention. Thus we should avoid null.

**Comment by li-boxuan** [comment]
According to coala [API](https://api.coala.io/en/latest/coalib.results.html#module-coalib.results.Result), ```First line is 1``` and ```First character is 1```. LSP uses the zero-based convention. 

If every bear conforms to coala convention, one should be subtracted from the line and character offset of the coala result before publishing diagnostics. However, some bears (e.g. PyLintBear) violates coala character offset convention, i.e. uses zero-based character offset (Luckily, their row numbers are one-based).These inconsistencies should be fixed first since LS should not and is not able to detect them.
