### ISSUE TITLE
.travis.yml: Remove unnecessary downloading of nltk data

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-vs-code#51]
The langserver now only runs on Python 3.4.4+, as that is the version supported by coala.

So the `if` in the following is unnecessary.

```
before_script:
  # nltk 3.2.2 dropped support for Python 3.3
  - >
    if [[ "$TRAVIS_PYTHON_VERSION" != "3.3" ]]; then
      python -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger
    fi
```

Also the relevant bear does install those data modules as required. And https://github.com/coala/coala-bears/pull/2398 is merged, so that bear can be enabled now.

**Comment by ksdme** [comment]
https://github.com/coala/coala-bears/pull/2398 does not seem to fix it all, https://travis-ci.org/coala/coala-vs-code/jobs/363403821#L713.

**Comment by ksdme** [comment]
Enabling GitCommitBear is causing the build failure, we might need to use the development version of coala-bears as of now.

**Comment by jayvdb** [comment]
Ya, I think this repo should use the development (git) version of bears (and coalib if necessary) in order that it can move quickly.

We'll try to get pre-releases happening soon which should reduce some of the instability of using git versions.
