### ISSUE TITLE
Fix docstring syntax

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-vs-code#56]
https://github.com/coala/coala-vs-code/commit/0b84584bd8b14b80e857417cc3a0edb0b2a93c45 broke the docstrings by using syntax

```diff
-    """Turn output to diagnstics."""
+    '""Turn output to diagnstics.""'
```

These need to be changed to using `"""`.  The bear doesnt like single line docstrings, so they need to be converted to multiline, or the bear replaced with `pydocstyle` bear.

**Comment by gaocegege** [comment]
@ksdme 

Are you interested in this issue?

**Comment by ksdme** [comment]
Yes, I will fix this issue.

**Comment by ksdme** [comment]
Much of the code is missing documentation so adding PyDocString to the list of bears leads to a string to issues.

**Comment by jayvdb** [comment]
Lots of cases to fix.
```
$ git grep \''""'
coala_langserver/diagnostic.py:    '""Turn output to diagnstics.""'
coala_langserver/langserver.py:    '""Language server for coala base on JSON RPC.""'
coala_langserver/langserver.py:        '""Handle the request from language client.""'
coala_langserver/langserver.py:        '""Serve for the initialization request.""'
coala_langserver/langserver.py:        '""Serve for did_change request.""'
coala_langserver/langserver.py:    #     '""Serve for the request of documentation changed.""'
coala_langserver/langserver.py:    #     '""Serve for thr workspace/didChangeWatchedFiles request.""'
coala_langserver/uri.py:    '""Get the path from JSON RPC initialization request.""'
coala_langserver/uri.py:    '""Get the directory name from the path.""'
```

**Comment by jayvdb** [comment]
> adding PyDocString to the list of bears leads to a string to issues.

You should be able to configure the bear to ignore codes.
