### ISSUE TITLE
coalashim_steps.py: Fix code styling

### ISSUE THREAD

**Issue by ksdme** [coala/coala-vs-code#65]
coala reports that ```tests/server.features/steps/coalashim_steps.py``` has some styling issue which need to be resolved.

**Comment by ksdme** [comment]
difficulty/newcomer

**Comment by wly5** [comment]
Hi! Can I try to take on this issue?

**Comment by gaocegege** [comment]
@wly5 Please follow the instruction to be the member of coala first, then I can assign the issue to you 🎉

**Comment by wly5** [comment]
Hi :) I read the newcomer documentation, joined the coala gitter app, and messaged Hello World in the chat. I was wondering how long it takes the bot to trigger?

**Comment by Ishaan28malik** [comment]
I would like to work on this issue

**Comment by gaocegege** [comment]
@Ishaan28malik

Sorry that the issue is blocked

**Comment by jayvdb** [comment]
This file has been removed from the repository
